In [19]:
import tensorflow as tf

In [20]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
print(tf.__version__)

2.1.0


In [22]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [23]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [31]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.16560812, -0.08066635, -0.31670216, -0.06377323, -0.11454625,
         0.12422235, -0.22142689, -0.1529522 ,  0.009115  , -0.11632517]],
      dtype=float32)

In [32]:
tf.nn.softmax(predictions).numpy()

array([[0.09394883, 0.10227774, 0.08077409, 0.10402021, 0.09887063,
        0.12553452, 0.0888484 , 0.0951454 , 0.11188521, 0.0986949 ]],
      dtype=float32)

In [33]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [34]:
loss_fn(y_train[:1], predictions).numpy()

2.0751746

In [36]:
model.compile(optimizer='adam',
              loss = loss_fn,
              metrics=['accuracy'])

In [37]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 4s 64us/sample - loss: 0.2974 - accuracy: 0.9137
Epoch 2/5
60000/60000 [==============================] - 3s 56us/sample - loss: 0.1420 - accuracy: 0.9584
Epoch 3/5
60000/60000 [==============================] - 3s 54us/sample - loss: 0.1106 - accuracy: 0.9665
Epoch 4/5
60000/60000 [==============================] - 3s 53us/sample - loss: 0.0875 - accuracy: 0.9734
Epoch 5/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.0754 - accuracy: 0.9761


In [38]:
model.evaluate(x_test, y_test, verbose=2)

10000/10000 - 0s - loss: 0.0740 - accuracy: 0.9780


[0.07402714014828671, 0.978]

In [39]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [40]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.72466374e-09, 3.27272237e-10, 5.15749491e-07, 5.05658754e-05,
        1.63969543e-12, 3.23470211e-08, 1.95640769e-12, 9.99946833e-01,
        1.30929698e-06, 6.64770312e-07],
       [1.38046312e-06, 2.36009888e-04, 9.99740660e-01, 6.30136174e-06,
        4.13706206e-13, 3.63726969e-07, 4.86623730e-06, 4.71418177e-15,
        1.03344337e-05, 1.00084065e-13],
       [6.59272985e-07, 9.99202073e-01, 8.53883830e-05, 9.12021005e-06,
        1.15424977e-04, 6.81822200e-07, 1.31872830e-05, 5.24561678e-04,
        4.73474611e-05, 1.41740418e-06],
       [9.99479234e-01, 1.47645256e-08, 2.06065615e-05, 4.65913974e-09,
        2.38239445e-05, 1.12376699e-06, 4.49149229e-04, 2.08970814e-05,
        1.22586794e-08, 5.21536958e-06],
       [5.34755543e-07, 6.09138573e-10, 3.26406678e-07, 3.62204133e-09,
        9.98819768e-01, 1.13437231e-07, 2.15964269e-06, 6.14519813e-05,
        1.07351070e-07, 1.11550314e-03]], dtype=float32)>